// fs0821_angular_spa/src/app/app.component.ts
import { Component } from '@angular/core';
import { NavigationEnd, Router } from '@angular/router';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent {
  currentUrl: string = ''

  title = 'fs0821_angular_spa';

  constructor(private router: Router,) {
    router.events.subscribe(event => {
      if (event instanceof NavigationEnd) {
        this.currentUrl = event.url
      }
    });
  }
}

<header class="container mx-auto py-8">
  <nav class="text-sm uppercase">
      <ul class="flex flex-row">
        <li [ngClass]="currentUrl == '/' ? 'font-bold' : ''" ><a routerLink="/" routerLinkActive="active">Grid</a></li>
        <li class="px-1">|</li>
        <li [ngClass]="currentUrl == '/payments' ? 'font-bold' : ''" ><a routerLink="/payments" routerLinkActive="active">Payments</a></li>
      </ul>
  </nav>    
</header>

<router-outlet></router-outlet>

// fs0821_react_spa/src/App.tsx
import React from 'react';
import { Outlet, Link, useLocation } from "react-router-dom";
import './App.css';

function App() {
  
  const { pathname }  = useLocation()
  return (
    <header className="container mx-auto py-8">
      <nav className="text-sm uppercase">
          <ul className="flex flex-row">
            <li className={['/', '/grid'].includes(pathname) ? 'font-bold': ''} ><Link to="/grid">Grid</Link></li>
            <li className="px-1">|</li>
            <li className={['/payments'].includes(pathname) ? 'font-bold': ''} ><Link to="/payments">Payments</Link></li>
          </ul>
      </nav>    
      <Outlet />
    </header>
  );
}

export default App;
