// fs0821_react_spa/src/routes/grid.tsx
import { KeyboardEvent, useContext, useState } from 'react';
import Clock from '../components/clock'
import { GridContext } from '../providers/grid';
export default function Grid() {

  const { state: { grid, code, generating, bias }, toggleGenerating = () => {}, setBias = () => {} } = useContext(GridContext);
  const [biasEnabled, setBiasEnabled] = useState(true);
  

  function onChangeBias(event: KeyboardEvent<HTMLInputElement>) {
    const key = event.key.toLocaleLowerCase()
    if (key.match(/^[a-z]$/)) {
      setBias(key)
      setBiasEnabled(false)
      setTimeout(() => setBiasEnabled(true), 4000)  
    } else {
      setBias('')
    }
  }


  return (

      <div className="container mx-auto py-4">
        
        <div className="flex flex-row justify-between align-bottom">
          <form>
            <label htmlFor="bias" className="block text-xs uppercase font-bold opacity-50">character</label>
            <input name="bias" value={bias} onChange={() => {}} onKeyDown={(event) => onChangeBias(event)} disabled={!biasEnabled} className="form-control border p-2 w-24" placeholder="Character" />
          </form>
          
          <Clock />
          
          <button className="border p-0 px-8 text-xs bg-slate-500 text-white font-bold h-10 rounded-md uppercase" onClick={() => toggleGenerating()}>
            { !generating ? 'generate 2d grid' : 'stop generator'}
          </button>

        </div>

        <div className="p-2" ></div>
        <div className="grid grid-cols-10">
          { grid.map((cell, index) => (
            <div className="border text-center p-2 whitespace-pre" key={index}>
              { cell }
            </div>  
          ))}
        </div>
        <div className="p-2" ></div>
        <div className="flex flex-row justify-center">
          <div className="w-fit justify-center font-bold text-sm" >
            <div className={`w-2 h-2 inline-block rounded-lg ${generating ? 'bg-green-500' : 'bg-red-200'}`} ></div>
            <div className="p-2 inline-block">LIVE </div>
          </div>
        </div>
        <div className="p-2" ></div>
        <div className="flex flex-row justify-center">
          <div className="border-2 p-4 px-16 w-fit justify-center text-sm" >YOUR CODE: <span className="font-bold">{ code }</span></div>
        </div>
        
      </div>


    );
  }

// fs0821_angular_spa/src/app/grid/grid.component.ts
import { Component, OnInit } from '@angular/core';
import { Store } from '@ngrx/store';
import { Observable, Subscription } from 'rxjs';
import { setBias, toggleGenerating } from '../grid.actions';
import { GridData } from '../grid.reducer';

@Component({
  selector: 'app-grid',
  templateUrl: './grid.component.html',
  styleUrls: ['./grid.component.css']
})
export class GridComponent implements OnInit {
  generating$: Observable<boolean>;
  grid$: Observable<Array<string>>;
  code$: Observable<string>

  bias: string = 'a'
  biasEnabled: boolean = true

  subscribeBias: Subscription

  constructor(private store: Store<{gridData: GridData}>) { 

    this.grid$ = this.store.select(state => state.gridData.grid)
    this.code$ = store.select(state => state.gridData.code)
    this.generating$ = store.select(state => state.gridData.generating)

    this.subscribeBias = this.store.select(state => state.gridData.bias).subscribe(value => {
      this.bias = value;
    })
  }

  ngOnInit(): void {

  }

  onToggleGenerator() {
    this.store.dispatch(toggleGenerating())
  }


  onChangeBias($event: KeyboardEvent) {
    if ($event.key.match(/^[a-z]$/)) {
      this.store.dispatch(setBias({ bias: $event.key }))  
    } else {
      this.bias = ''
      this.store.dispatch(setBias({ bias: '' }))  
    }

    // disabling for 4secs
    if (this.bias.length > 0) {
      this.biasEnabled = false
      setTimeout(() => this.biasEnabled = true, 4000)  
    }
  }

}

<div class="container mx-auto">
  
    <div class="flex flex-row justify-between align-bottom">
      <form>
        <label for="bias" class="block text-xs uppercase font-bold opacity-50">character</label>
        <input name="bias" maxlength="1" class="form-control border p-2 w-24" [disabled]="!biasEnabled" [ngModel]="bias" (keydown)="onChangeBias($event)" placeholder="Character">
      </form>
      
      <app-clock></app-clock>
      
      <button class="border p-0 px-8 text-xs bg-slate-500 text-white font-bold h-10 rounded-md uppercase" (click)="onToggleGenerator()">
          {{ !(generating$ | async) ? 'generate 2d grid' : 'stop generator'}}
      </button>
    
    </div>
  
    <div class="p-2" ></div>
    <div class="grid grid-cols-10">
      <div *ngFor="let cell of grid$ | async " class="border text-center p-2 whitespace-pre">
        {{ cell }}
      </div>  
    </div>
    <div class="p-2" ></div>
    <div class="flex flex-row justify-center">
      <div class="w-fit justify-center font-bold text-sm" >
        <div class="w-2 h-2 inline-block rounded-lg" [ngClass]="(generating$ | async) ? 'bg-green-500' : 'bg-red-200'"></div>
        <div class="p-2 inline-block">LIVE </div>
      </div>
    </div>
    <div class="p-2" ></div>
    <div class="flex flex-row justify-center">
      <div class="border-2 p-4 px-16 w-fit justify-center text-sm" >YOUR CODE: <span class="font-bold">{{ code$ | async }}</span></div>
    </div>
    
  </div>
